### ISSUE TITLE
BIR Registration of OSIRiS

### ISSUE THREAD

**Issue by BSITSA** [HBSIph/OSIRiS-Implementation#10]
Ms. Lovelle said that when she went to BIR Baguio to process their continuous-paper receipt, BIR asked her to verify if the system that they are using to generate receipt is already registered to BIR.

**Comment by kimPM** [comment]
Hi, they could just reply to BIR that they will be using the OR in continuous paper to be able to print OR details using a printer. It is not really necessary for them to declare that they are using a system. Thanks.
